---
title: "PROJECT TITLE"
author: "24-7"
date: "4-20-18"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r - install_packages}
library(tidyverse)
library(readxl)
library(stringr)
library(lubridate)
library(maps)
library(Metrics)
library(shiny)
```

```{r-seed}
set.seed(1234)
```


```{r join-data, echo = FALSE, message=FALSE}
h2b2008 <- read_csv("data/H-2B_FY2008.csv") %>%
  mutate(year = 2008)
h2b2009 <- read_csv("data/H-2B_FY2009.csv") %>%
  mutate(year = 2009)
h2b2010 <- read_csv("data/H-2B_FY2010.csv") %>%
  mutate(year = 2010)
h2b2011 <- read_csv("data/H-2B_FY2011.csv") %>%
  mutate(year = 2011)
h2b2012 <- read_csv("data/H-2B_FY2012.csv") %>%
  mutate(year = 2012)

h2b <- h2b2008 %>%
  full_join(h2b2009) %>%
  full_join(h2b2010)%>%
  full_join(h2b2011)%>%
  full_join(h2b2012)

h2b <- h2b %>%
  select(year, CASE_NO, DECISION_DATE, NPC_SUBMITTED_DATE, CASE_STATUS, ALIEN_WORK_STATE, CERTIFICATION_BEGIN_DATE, CERTIFICATION_END_DATE, EMPLOYER_CITY, EMPLOYER_STATE, EMPLOYER_POSTAL_CODE, AGENT_ATTORNEY_CITY, AGENT_ATTORNEY_STATE, JOB_TITLE, NBR_WORKERS_CERTIFIED, PREVAILING_WAGE, PW_UNIT_OF_PAY, BASIC_RATE_OF_PAY, BASIC_UNIT_OF_PAY, DOT_OCCUPATIONAL_CODE, NBR_WORKERS_REQUESTED, DOT_NAME, SOC_CODE, SOC_NAME)
```

### Background

### Data Manipulation
```{r - uncapitalize_variables}
h2b <- h2b %>%
  mutate(case_no = CASE_NO, 
         decision_date = DECISION_DATE,
         npc_submitted_date = NPC_SUBMITTED_DATE,
         case_status = CASE_STATUS, 
         alien_work_state = ALIEN_WORK_STATE, 
         certification_begin_date = CERTIFICATION_BEGIN_DATE, 
         certification_end_date = CERTIFICATION_END_DATE, 
         employer_city = EMPLOYER_CITY, 
         employer_state = EMPLOYER_STATE, 
         employer_postal_code = EMPLOYER_POSTAL_CODE, 
         agent_attorney_city = AGENT_ATTORNEY_CITY, 
         agent_attorney_state = AGENT_ATTORNEY_STATE, 
         job_title = JOB_TITLE, 
         nbr_workers_certified = NBR_WORKERS_CERTIFIED, 
         prevailing_wage = PREVAILING_WAGE, 
         pw_unit_of_pay = PW_UNIT_OF_PAY, 
         basic_rate_of_pay = BASIC_RATE_OF_PAY, 
         basic_unit_of_pay = BASIC_UNIT_OF_PAY, 
         dot_occupational_code = DOT_OCCUPATIONAL_CODE, 
         nbur_workers_requested =NBR_WORKERS_REQUESTED, 
         dot_name = DOT_NAME, 
         soc_code = SOC_CODE, 
         soc_name = SOC_NAME)

h2b <- h2b %>%
  select(year, case_no, decision_date, npc_submitted_date, case_status, alien_work_state, certification_begin_date, certification_end_date, employer_city, employer_state, employer_postal_code, agent_attorney_city, agent_attorney_state, job_title, nbr_workers_certified, prevailing_wage, pw_unit_of_pay, basic_rate_of_pay, basic_unit_of_pay, dot_occupational_code, nbur_workers_requested, dot_name, soc_code, soc_name)

```


```{r - muate_benefits}

h2b <- h2b %>%
  mutate(wage_diff = case_when(
  prevailing_wage > basic_rate_of_pay ~ "prevail_higher",
  prevailing_wage == basic_rate_of_pay ~ "same",
  prevailing_wage < basic_rate_of_pay ~ "basic_higher"
  ))
  

```

```{r - mutate_season}
h2b <- h2b %>%
  mutate(decision_season = case_when(
    str_sub(decision_date,1,2) == "1/" ~ "winter",
    str_sub(decision_date,1,2) == "2/" ~ "winter",
    str_sub(decision_date,1,2) == "3/" ~ "spring",
    str_sub(decision_date,1,2) == "4/" ~ "spring",
    str_sub(decision_date,1,2) == "5/" ~ "spring",
    str_sub(decision_date,1,2) == "6/" ~ "summer",
    str_sub(decision_date,1,2) == "7/" ~ "summer",
    str_sub(decision_date,1,2) == "8/" ~ "summer",
    str_sub(decision_date,1,2) == "9/" ~ "fall",
    str_sub(decision_date,1,3) == "10/" ~ "fall",
    str_sub(decision_date,1,3) == "11/" ~ "fall",
    str_sub(decision_date,1,3) == "12/" ~ "winter",
    str_sub(decision_date,3,5) == "Jan" ~ "winter",
    str_sub(decision_date,4,6) == "Jan" ~ "winter",
    str_sub(decision_date,3,5) == "Feb" ~ "winter",
    str_sub(decision_date,4,6) == "Feb" ~ "winter",
    str_sub(decision_date,3,5) == "Mar" ~ "spring",
    str_sub(decision_date,4,6) == "Mar" ~ "spring",
    str_sub(decision_date,3,5) == "Apr" ~ "spring",
    str_sub(decision_date,4,6) == "Apr" ~ "spring",
    str_sub(decision_date,3,5) == "May" ~ "spring",
    str_sub(decision_date,4,6) == "May" ~ "spring",
    str_sub(decision_date,3,5) == "Jun" ~ "summer",
    str_sub(decision_date,4,6) == "Jun" ~ "summer",
    str_sub(decision_date,3,5) == "Jul" ~ "summer",
    str_sub(decision_date,4,6) == "Jul" ~ "summer",
    str_sub(decision_date,3,5) == "Aug" ~ "summer",
    str_sub(decision_date,4,6) == "Aug" ~ "summer",
    str_sub(decision_date,3,5) == "Sep" ~ "fall",
    str_sub(decision_date,4,6) == "Sep" ~ "fall",
    str_sub(decision_date,3,5) == "Oct" ~ "fall",
    str_sub(decision_date,4,6) == "Oct" ~ "fall",
    str_sub(decision_date,3,5) == "Nov" ~ "fall",
    str_sub(decision_date,4,6) == "Nov" ~ "fall",
    str_sub(decision_date,3,5) == "Dec" ~ "winter",
    str_sub(decision_date,4,6) == "Dec" ~ "winter",
  ))

h2b <- h2b %>%
  mutate(submitted_season = case_when(
    str_sub(npc_submitted_date,1,2) == "1/" ~ "winter",
    str_sub(npc_submitted_date,1,2) == "2/" ~ "winter",
    str_sub(npc_submitted_date,1,2) == "3/" ~ "spring",
    str_sub(npc_submitted_date,1,2) == "4/" ~ "spring",
    str_sub(npc_submitted_date,1,2) == "5/" ~ "spring",
    str_sub(npc_submitted_date,1,2) == "6/" ~ "summer",
    str_sub(npc_submitted_date,1,2) == "7/" ~ "summer",
    str_sub(npc_submitted_date,1,2) == "8/" ~ "summer",
    str_sub(npc_submitted_date,1,2) == "9/" ~ "fall",
    str_sub(npc_submitted_date,1,3) == "10/" ~ "fall",
    str_sub(npc_submitted_date,1,3) == "11/" ~ "fall",
    str_sub(npc_submitted_date,1,3) == "12/" ~ "winter",
    str_sub(npc_submitted_date,3,5) == "Jan" ~ "winter",
    str_sub(npc_submitted_date,4,6) == "Jan" ~ "winter",
    str_sub(npc_submitted_date,3,5) == "Feb" ~ "winter",
    str_sub(npc_submitted_date,4,6) == "Feb" ~ "winter",
    str_sub(npc_submitted_date,3,5) == "Mar" ~ "spring",
    str_sub(npc_submitted_date,4,6) == "Mar" ~ "spring",
    str_sub(npc_submitted_date,3,5) == "Apr" ~ "spring",
    str_sub(npc_submitted_date,4,6) == "Apr" ~ "spring",
    str_sub(npc_submitted_date,3,5) == "May" ~ "spring",
    str_sub(npc_submitted_date,4,6) == "May" ~ "spring",
    str_sub(npc_submitted_date,3,5) == "Jun" ~ "summer",
    str_sub(npc_submitted_date,4,6) == "Jun" ~ "summer",
    str_sub(npc_submitted_date,3,5) == "Jul" ~ "summer",
    str_sub(npc_submitted_date,4,6) == "Jul" ~ "summer",
    str_sub(npc_submitted_date,3,5) == "Aug" ~ "summer",
    str_sub(npc_submitted_date,4,6) == "Aug" ~ "summer",
    str_sub(npc_submitted_date,3,5) == "Sep" ~ "fall",
    str_sub(npc_submitted_date,4,6) == "Sep" ~ "fall",
    str_sub(npc_submitted_date,3,5) == "Oct" ~ "fall",
    str_sub(npc_submitted_date,4,6) == "Oct" ~ "fall",
    str_sub(npc_submitted_date,3,5) == "Nov" ~ "fall",
    str_sub(npc_submitted_date,4,6) == "Nov" ~ "fall",
    str_sub(npc_submitted_date,3,5) == "Dec" ~ "winter",
    str_sub(npc_submitted_date,4,6) == "Dec" ~ "winter",
  ))
```


```{r-mutate_region}
h2b <- h2b %>%
  mutate(region = case_when(
    employer_state == "WA" | employer_state == "OR" | employer_state == "CA" |  employer_state == "ID" | employer_state == "MT" | employer_state == "WY" | employer_state == "NV" | employer_state == "UT" | employer_state == "CO" | employer_state == "AZ" | employer_state == "NM" | employer_state == "AK" | employer_state == "HI" ~ "West",
    employer_state == "ND" | employer_state == "SD" | employer_state == "NE" | employer_state == "KS" | employer_state == "MN" | employer_state == "IA" | employer_state == "MO" | employer_state == "WI" | employer_state == "IL" | employer_state == "MI" | employer_state == "IN" | employer_state == "OH" ~ "Midwest",
    employer_state == "TX" | employer_state == "OK" | employer_state == "AR" | employer_state == "LA" | employer_state == "MS" | employer_state == "AL" | employer_state == "TN" | employer_state == "KY" | employer_state == "WV" | employer_state == "MD" | employer_state == "DE" | employer_state == "VA" | employer_state == "NC" | employer_state == "SC" | employer_state == "GA" | employer_state == "FL" ~ "South",
    employer_state == "ME" | employer_state == "NH" | employer_state == "VT" | employer_state == "MA" | employer_state == "CT" | employer_state == "RI" | employer_state == "NJ" | employer_state == "NY" | employer_state == "PA" ~ "Northeast"
  ))
```

```{r-mutate_job_categories}
h2b <- h2b %>%
  mutate(occupation_category = case_when(
    str_sub(dot_occupational_code,1,1) == "0" | str_sub(dot_occupational_code,1,1) == "1" ~ "professional, technical, and managerial",
    str_sub(dot_occupational_code,1,1) == "2" ~ "clerical and sales",
    str_sub(dot_occupational_code,1,1) == "3" ~ "service",
    str_sub(dot_occupational_code,1,1) == "4" ~ "agricultural, fishery, forestry, and related",
    str_sub(dot_occupational_code,1,1) == "5" ~ "processing",
    str_sub(dot_occupational_code,1,1) == "6" ~ "machine trades",
    str_sub(dot_occupational_code,1,1) == "7" ~ "benchwork",
    str_sub(dot_occupational_code,1,1) == "8" ~ "structural work",
    str_sub(dot_occupational_code,1,1) == "9" ~ "miscellaneous"
  ))

```

### Visualizations
```{r - map}
state_props <- h2b %>%
  filter(!is.na(nbur_workers_requested) & !(is.na(nbr_workers_certified))) %>%
  filter(employer_state %in% state.abb | employer_state == "DC") %>%
  filter(employer_state != "HI" & employer_state!="AK") %>%
  mutate(region = case_when(employer_state %in% state.abb ~ tolower(setNames(state.name, state.abb))[employer_state], employer_state == "DC" ~ "district of columbia")) %>%
  group_by(region) %>%
  summarise(prop = sum(nbr_workers_certified) / sum(nbur_workers_requested))

#h2b %>%
  #filter(!is.na(nbur_workers_requested) & !(is.na(nbr_workers_certified))) %>%
  #group_by(employer_state) %>%
  #summarise(prop = sum(nbr_workers_certified) / sum(nbur_workers_requested),
   #         n = n()) %>%
  #arrange(desc(prop))

#h2b %>%
 # filter(!is.na(nbur_workers_requested) & !(is.na(nbr_workers_certified))) %>%
  #group_by(employer_state) %>%
  #summarise(prop = sum(nbr_workers_certified) / sum(nbur_workers_requested),
   #         n = n()) %>%
  #arrange(prop)

map <- merge(state_props, map_data("state"), sort = FALSE, by = "region")

map %>%
  ggplot() + 
  geom_polygon(aes(x = long, y = lat, group = group, fill = prop), color = "white") +
  coord_fixed(1.5) + 
  labs(title = "Proportion of H2B visa applications approved",
       subtitle = "By state",
       x = "Longitude",
       y = "Latitude",
       fill = "Proportion approved")
  
#map_data("state") %>%
 # ggplot() +
  #geom_polygon(aes(x = long, y = lat, group = group), color = "white")
```

```{r line-graph}
h2b %>% 
  filter(case_status %in% c("CERTIFIED", "PARTIAL CERTIFIED", "DENIED")) %>%
  group_by(year) %>%
  count(case_status) %>%
  ggplot(mapping = aes(x = year, y = n, color = case_status)) +
  geom_point() + 
  geom_line() +
  labs(title = "Decrease in number of H2B visas certified",
       subtitle = "From 2008 to 2012",
       x = "Year",
       y = "Number",
       color = "Application Result")
```

In 2008, Congress failed to renew the Save Our Small and Seasonal Bussinesses Act (SOSSBA). This reduced the cap for the total number of H2B Visas that could be approved every year. 

### Regression Model
```{r-mutate-prop-certified}
h2b <- h2b %>%
  mutate(prop_workers_certified = nbr_workers_certified/nbur_workers_requested) 
```

```{r-backwards-selection}
mod <- lm(prop_workers_certified ~ occupation_category + prevailing_wage + submitted_season + region + nbur_workers_requested, data = h2b)

selected_mod <- step(mod, direction = "backward")

(selected_mod)
```

###Shiny

```{r map-wage}
state_wages <- h2b %>%
  filter(!is.na(basic_rate_of_pay) & !(is.na(basic_unit_of_pay))) %>%
  filter(employer_state %in% state.abb | employer_state == "DC") %>%
  filter(employer_state != "HI" & employer_state!="AK") %>%
  filter(basic_unit_of_pay == "HR") %>%
  mutate(region = case_when(employer_state %in% state.abb ~ tolower(setNames(state.name, state.abb))[employer_state], employer_state == "DC" ~ "district of columbia")) %>%
  group_by(region) %>%
  summarise(median_wage = median(basic_rate_of_pay))

map <- merge(state_wages, map, sort = FALSE, by = "region")
```

```{r map-occupation}
state_occ <- h2b %>%
  filter(!is.na(occupation_category)) %>%
  filter(employer_state %in% state.abb | employer_state == "DC") %>%
  filter(employer_state != "HI" & employer_state!="AK") %>%
  mutate(region = case_when(employer_state %in% state.abb ~ tolower(setNames(state.name, state.abb))[employer_state], employer_state == "DC" ~ "district of columbia")) %>% 
   group_by(region) %>%
   count(region, occupation_category) %>%
  slice(which.max(n))

map <- merge(state_occ, map, sort = FALSE, by = "region")

```

```{r map-season}
state_season <- h2b %>%
  filter(!is.na(submitted_season)) %>%
  filter(employer_state %in% state.abb | employer_state == "DC") %>%
  filter(employer_state != "HI" & employer_state!="AK") %>%
  mutate(region = case_when(employer_state %in% state.abb ~ tolower(setNames(state.name, state.abb))[employer_state], employer_state == "DC" ~ "district of columbia")) %>% 
   group_by(region) %>%
   count(region, submitted_season) %>%
  slice(which.max(n))

map <- merge(state_season, map, sort = FALSE, by = "region")
```

```{r map-total}
state_total <- h2b %>%
  filter(employer_state %in% state.abb | employer_state == "DC") %>%
  filter(employer_state != "HI" & employer_state!="AK") %>%
  mutate(region = case_when(employer_state %in% state.abb ~ tolower(setNames(state.name, state.abb))[employer_state], employer_state == "DC" ~ "district of columbia")) %>% 
   group_by(region) %>%
   summarise(n = n())

map <- merge(state_total, map, sort = FALSE, by = "region")
```


```{r shiny-map}
ui <- fluidPage(
      titlePanel("H2B visas by state"),
      sidebarLayout(
        sidebarPanel(
          selectInput(inputId = "fill", label = "Fill Map By",
          choices = c("Proportion approved" = "prop",
                      "Total applications" = "n", 
                      "Median hourly wage" = "median_wage",
                      "Most popular occupation" = "occupation_category",
                      "Most popular season" = "submitted_season"),
          selected = "Proportion approved")
        ),
       mainPanel(
         plotOutput(outputId = "map")
       )
      )
      
  )

server <- function(input, output) {
  output$map <- renderPlot({
  ggplot(data = map) + 
  geom_polygon(aes_string(x = "long", y = "lat", group = "group", fill = input$fill), color = "white") +
  coord_fixed(1.5) + 
  labs(
       x = "Longitude",
       y = "Latitude"
       )
  })
}

shinyApp(ui = ui, server = server)
```




